### ISSUE TITLE
sidedness

### ISSUE THREAD

**Issue by kreezxil** [JibayMcs/Ama-s-Damage-Indicator#3]
is it necessary to have the mod on the server too?

your mods.toml shows the sidedness to be both

![image](https://user-images.githubusercontent.com/3880072/75462391-ce7cee00-5949-11ea-8897-59a5a7e53783.png)

**Comment by JibayMcs** [comment]
Yes, because I use packets

**Comment by kreezxil** [comment]
ok, but I ask because the mod only seems to effectively show damage
indication to me. Are you also showing said damage indication that I
inflict to other players in my vicinity?

**Comment by JibayMcs** [comment]
Usually yes

**Comment by kreezxil** [comment]
ok, that is understandable to me. you may close this now.
